name: SimplyHealth Cypress Tests
on: push
jobs:
   install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
                uses: npi ci
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser : chrome
          headless : true
          start : npm run dev

